module.exports = {
  darkMode: ['selector'],
  theme: {
    container: {
      center: true,
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      fontFamily: {
        sans: [
          'var(--layout-text-font-family)',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          '"Helvetica Neue"',
          'Arial',
          '"Noto Sans"',
          'sans-serif',
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
        serif: ['var(--font-serif)', 'ui-serif', 'Georgia', 'Cambria', '"Times New Roman"', 'Times', 'serif'],
        mono: [
          'var(--font-mono)',
          'ui-monospace',
          'SFMono-Regular',
          'Menlo',
          'Monaco',
          'Consolas',
          '"Liberation Mono"',
          '"Courier New"',
          'monospace',
        ],
      },
      colors: {
        blue: {
          100: '#dfefff',
          200: '#bfdfff',
          300: '#8ec8ff',
          400: '#4aa3f9',
          500: '#1683ec',
          600: '#1269bd',
          700: '#0d478e',
          800: '#092e62',
          900: '#05183d',
          DEFAULT: '#1683ec',
        },
        green: {
          100: '#e6fff4',
          200: '#aaffdd',
          300: '#7ae9c6',
          400: '#36d29e',
          500: '#10b780',
          600: '#0e9566',
          700: '#0b734d',
          800: '#085333',
          900: '#05331f',
          DEFAULT: '#10b780',
        },
        purple: {
          100: '#f0e6ff',
          200: '#d9bfff',
          300: '#c1a3ff',
          400: '#a78bfa',
          500: '#8b5cf6',
          600: '#6f46d1',
          700: '#552fb0',
          800: '#3b1f80',
          900: '#281259',
          DEFAULT: '#8b5cf6',
        },
        yellow: {
          100: '#fff5d6',
          200: '#feeaa9',
          300: '#ffd963',
          400: '#f0bd1f',
          500: '#d19e00',
          600: '#a07904',
          700: '#825f04',
          800: '#624502',
          900: '#432d02',
          DEFAULT: '#d19e00',
        },
        red: {
          100: '#ffe6e6',
          200: '#ffbfbf',
          300: '#ff8a8a',
          400: '#f87171',
          500: '#ef4444',
          600: '#c93737',
          700: '#a22929',
          800: '#7a1c1c',
          900: '#5b1010',
          DEFAULT: '#ef4444',
        },
        basic: {
          100: '#ffffff',
          200: '#fafafa',
          300: '#f4f4f5',
          400: '#d4d5d8',
          500: '#b7b8bd',
          600: '#898a8f',
          700: '#606164',
          800: '#48494d',
          900: '#363639',
          1000: '#1e1e20',
          1100: '#09090b',
          DEFAULT: '#606164',
        },
        stroke: {
          basic: '#09090b1f',
          dark: '#09090b33',
          light: '#09090b12',
        },
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          1: 'hsl(var(--chart-1))',
          2: 'hsl(var(--chart-2))',
          3: 'hsl(var(--chart-3))',
          4: 'hsl(var(--chart-4))',
          5: 'hsl(var(--chart-5))',
        },
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar-background))',
          foreground: 'hsl(var(--sidebar-foreground))',
          primary: 'hsl(var(--sidebar-primary))',
          'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
          accent: 'hsl(var(--sidebar-accent))',
          'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
          border: 'hsl(var(--sidebar-border))',
          ring: 'hsl(var(--sidebar-ring))',
        },
      },
      borderRadius: {
        sm: 'calc(var(--radius) - 6px)',
        DEFAULT: 'calc(var(--radius) - 4px)',
        md: 'calc(var(--radius) - 2px)',
        lg: 'var(--radius)',
        xl: 'calc(var(--radius) + 4px)',
        '2xl': 'calc(var(--radius) + 8px)',
        '3xl': 'calc(var(--radius) + 12px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        'slide-from-left': {
          '0%': {
            transform: 'translateX(-100%)',
          },
          '100%': {
            transform: 'translateX(0)',
          },
        },
        'slide-to-left': {
          '0%': {
            transform: 'translateX(0)',
          },
          '100%': {
            transform: 'translateX(-100%)',
          },
        },
      },
      animation: {
        'slide-from-left': 'slide-from-left 0.3s cubic-bezier(0.82, 0.085, 0.395, 0.895)',
        'slide-to-left': 'slide-to-left 0.25s cubic-bezier(0.82, 0.085, 0.395, 0.895)',
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
